version: '3'
services:
  docker_gen:
    image: karlyan/docker-gen-cert-bot
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/net/docker_tmp/crt:/crt"
      - "nginx-srv:/srv"
volumes:
  nginx-srv:
